### ISSUE TITLE
Trying to create tensor with negative dimension -2: [-2, 34, 3, 3]

### ISSUE THREAD

**Issue by dronefreak** [wvangansbeke/Sparse-Depth-Completion#38]
Hello,

Upon executing the `model.py`, I am getting the following traceback:

```
Traceback (most recent call last):
  File "model.py", line 169, in <module>
    model = uncertainty_net(34, in_channels).cuda()
  File "model.py", line 23, in __init__
    self.depthnet = Net(in_channels=in_channels, out_channels=out_channels)
  File "/home/saum/7sensing/Sparse-Depth-Completion/Models/ERFNet.py", line 143, in __init__
    self.encoder = Encoder(in_channels, out_channels)
  File "/home/saum/7sensing/Sparse-Depth-Completion/Models/ERFNet.py", line 66, in __init__
    self.initial_block = DownsamplerBlock(in_channels, chans)
  File "/home/saum/7sensing/Sparse-Depth-Completion/Models/ERFNet.py", line 15, in __init__
    self.conv = nn.Conv2d(ninput, noutput-ninput, (3, 3), stride=2, padding=1, bias=True)
  File "/home/saum/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in __init__
    False, _pair(0), groups, bias, padding_mode)
  File "/home/saum/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 52, in __init__
    out_channels, in_channels // groups, *kernel_size))
RuntimeError: Trying to create tensor with negative dimension -2: [-2, 34, 3, 3]
```
Could you help in this regard?

**Comment by wvangansbeke** [comment]
Hi @dronefreak,

Good catch. There was a typo. It should be fixed now.
