### ISSUE TITLE
num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by abhishekk06** [wvangansbeke/Sparse-Depth-Completion#43]
**Not able to run training.** Please help me figure out what went wrong.

Cmd line:- Sparse-Depth-Completion$ `python main.py --data_path ../../dataset/train/kitti_lookalike/ --lr_policy plateau --num_samples 128000`

Traceback (most recent call last):
  File "main.py", line 437, in <module>
    main()
  File "main.py", line 171, in main
    train_loader, valid_loader, valid_selection_loader = get_loader(args, dataset)
  File "/home/mdl/azk6085/MDL/Sparse-Depth-Completion/Datasets/dataloader.py", line 54, in get_loader
    pin_memory=True, drop_last=True)
  File "/home/mdl/azk6085/sw_package/anaconda/envs/tensorflow/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)
  File "/home/mdl/azk6085/sw_package/anaconda/envs/tensorflow/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 94, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by wvangansbeke** [comment]
Hi @abhishekk06,

Thank you for your interest.
It should be 0 to use the standard setup.

**Comment by abhishekk06** [comment]
Hi @wvangansbeke 

I tried running without "--num_samples" and I still get the same error. BTW it is my own dataset and not KITTI. 


`python main.py --data_path ../../train/kitti_lookalike/ --lr_policy plateau
Init weights in network with [kaiming]
0
0
0
0
0
0
128000
128000
num samplesNone
DataloaderNone
DataloaderNone
DataloaderNone
Traceback (most recent call last):
  File "main.py", line 437, in <module>
    main()
  File "main.py", line 171, in main
    train_loader, valid_loader, valid_selection_loader = get_loader(args, dataset)
  File "/home/mdl/azk6085/MDL/Sparse-Depth-Completion/Datasets/dataloader.py", line 54, in get_loader
    pin_memory=True, drop_last=True)
  File "/home/mdl/azk6085/sw_package/anaconda/envs/tensorflow/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)
  File "/home/mdl/azk6085/sw_package/anaconda/envs/tensorflow/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 94, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
`

**Comment by abhishekk06** [comment]
Hi 

Can you please take a look? I am not sure if i am missing anything in environment.  I am not able to train the network in new dataset

**Comment by wvangansbeke** [comment]
Hi,

I can't seem to reproduce it. Please react if this issue is still relevant to you. Closing this for now.
